config/routes.rb
Rails.application.routes.draw do
  root to: "kittens#index"
  resources :kittens

  get "image_chest" => "image_chest#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/image_chest_controller.rb
require 'rest-client'
class ImageChestController < ApplicationController

  def show
    unless params[:post_id].blank?
      post = RestClient.get("https://api.imgchest.com/v1/post/#{params[:post_id]}", { Authorization: "Bearer #{ENV['IMGCHEST_TOKEN']}" })
      @images = []
      JSON.parse(post.body)['data']['images'].each { |file| @images << file['link'] }
    end
    render :show
  end
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to kitten_path(@kitten), notice: "New kitten has been created"
    else
      flash.now[:alert] = "Invalid input"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to kitten_path(@kitten), notice: "Kitten has been updated"
    else
      flash.now[:alert] = "Invalid input"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    redirect_to kittens_path, notice: "Kitten has been deleted"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_chest_helper.rb
module ImageChestHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/image_chest/show.html.erb
<h1>Images</h1>
<%= form_with url: 'image_chest', method: :get do |f|%>
  <%= f.text_field :post_id %>
  <%= f.submit 'Submit'%>
<% end %>
<% unless @images.nil? || @images.empty? %>
  <% @images.each do |img| %>
    <%= image_tag img, style: "width: 720px; height: auto;" %>
  <% end %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
<div>Name: <%= @kitten.name %></div>
<div>Age: <%= @kitten.age %></div>
<div>Cuteness: <%= @kitten.cuteness %></div>
<div>Softness: <%= @kitten.softness %></div>
<div>
  <%= form_with model: @kitten, local: true, method: 'put' do |f|%>
    <%= f.label :name, 'New Name:' %>
    <%= f.text_field :name %>
    <%= f.label :age, 'New Age:' %>
    <%= f.number_field(:age, step: 1) %>
    <%= f.label :cuteness, 'New Cuteness:' %>
    <%= f.number_field(:cuteness, step: 1) %>
    <%= f.label :softness, 'New Softness:' %>
    <%= f.number_field(:softness, step: 1) %>
    <%= f.submit 'Submit' %>
  <% end %>
</div>
<%= link_to 'Delete this kitten', kitten_path(@kitten), data: { turbo_method: "delete" }  %>

app/views/kittens/index.html.erb
<h1>Kittens Index</h1>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
<%= link_to 'New Kitten', new_kitten_path %>
<ul>
  <% @kittens.each do |kitten| %>
    <li> <%= link_to kitten.name, kitten_path(kitten) %> <%= link_to 'delete this kitten', kitten_path(kitten), data: { turbo_method: "delete" }  %></li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
<%= form_with model: @kitten, local: true do |f|%>
  <%= f.label :name, 'Name:' %>
  <%= f.text_field :name %>
  <%= f.label :age, 'Age:' %>
  <%= f.number_field(:age, step: 1) %>
  <%= f.label :cuteness, 'Cuteness:' %>
  <%= f.number_field(:cuteness, step: 1) %>
  <%= f.label :softness, 'Softness:' %>
  <%= f.number_field(:softness, step: 1) %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/kittens/show.html.erb
<h1>Show Kitten</h1>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
<div>Name: <%= @kitten.name %></div>
<div>Age: <%= @kitten.age %></div>
<div>Cuteness: <%= @kitten.cuteness %></div>
<div>Softness: <%= @kitten.softness %></div>
<%= link_to 'Delete this kitten', kitten_path(@kitten), data: { turbo_method: "delete" }  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>